# Build orchestration for the out-of-tree route-mpls module.
#
# Prerequisite: a configured and built yanet2 checkout that carries the
# module SDK (the feat/module-sdk branch or its successor): from the
# checkout root run `make sdk` once.
#
# YANET_ROOT points the build at the yanet2 checkout this module is built
# against. The default assumes this repository sits at external/route-mpls
# inside the checkout; override it when building from elsewhere (and adjust
# the go.mod replace directive and the cli/ path dependencies likewise —
# see README.md).
YANET_ROOT ?= $(realpath ../..)
SDK_PC_DIR := $(YANET_ROOT)/build/sdk

# Keep the caller's pkg-config search path intact while adding the SDK.
export PKG_CONFIG_PATH := $(SDK_PC_DIR)$(if $(PKG_CONFIG_PATH),:$(PKG_CONFIG_PATH),)

# The shared structs are alignment-sensitive: the cache-line size must match
# the dataplane build the module is compiled against.
RTE_CONFIG ?= $(YANET_ROOT)/build/subprojects/dpdk/rte_build_config.h
CACHE_LINE_SIZE := $(shell awk '$$2 == "RTE_CACHE_LINE_SIZE" { print $$3; exit }' "$(RTE_CONFIG)")
export CGO_CPPFLAGS += -DYANET_CACHE_LINE_SIZE=$(CACHE_LINE_SIZE)

# Build the CLI through the checkout's target directory so its binaries
# land next to the in-tree ones.
CARGO_TARGET_DIR ?= $(YANET_ROOT)/target
export CARGO_TARGET_DIR

PROTO_DIR := controlplane/routemplspb/v1

.PHONY: \
	all \
	meson \
	protoc \
	go \
	cli \
	test \
	clean

all: meson protoc go cli

# Dataplane plugin (libroute_mpls_dp.so) and control-plane FFI archive
# (libroute_mpls_cp.a), through the SDK pkg-config metadata generated by
# the yanet2 build.
meson:
	@if [ -d build ]; then \
		meson compile -C build; \
	else \
		meson setup build && meson compile -C build; \
	fi

# Generated protobuf code, written into the source tree like in-tree
# modules (and gitignored the same way).
protoc:
	protoc \
		-I $(PROTO_DIR) \
		-I $(YANET_ROOT) \
		--go_out=paths=source_relative:$(PROTO_DIR) \
		--go-grpc_out=paths=source_relative:$(PROTO_DIR) \
		$(PROTO_DIR)/routempls.proto

# Control plane and daemon; needs the yanet2 checkout's C archives and
# generated protobuf code in place.
go: meson protoc
	go build ./...

# Module CLI as a standalone workspace, so the yanet2 workspace never
# grows a member it does not ship.
cli:
	cargo build --release --manifest-path cli/Cargo.toml

# Unit and functional tests; the functional test loads the plugin into the
# in-process dataplane harness and drives the control plane through the
# module bindings.
test: go
	go test -count=1 ./...

clean:
	rm -rf build
